# Generated by Django 5.0.6 on 2024-06-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_answer_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='auther',
            new_name='author',
        ),
    ]
